{% set name = "sirius" %}
{% set version = "7.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/electronic-structure/SIRIUS/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aeed0e83b80c3a79a9469e7f3fe10d80ad331795e38dbc3c49cb0308e2bd084d
  patches:
    - fix_osx_compilation.patch  # [osx]

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_compatible('sirius', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - make
    - cmake >=3.14.0
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
  host:
    - {{ mpi }}
    - libblas
    - liblapack
    - gsl
    - libxc
    - spglib
    - hdf5
    - spfft
    - spla
    - boost-cpp    # [osx]
    - pkg-config
    - scalapack
  run:
    - {{ mpi }}
    - scalapack
    - spfft
    - spla
    - boost-cpp    # [osx]

test:
  commands:
    - test -f "${PREFIX}/lib/libsirius${SHLIB_EXT}"

about:
  home: https://github.com/electronic-structure/SIRIUS
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Domain specific library for electronic structure calculations
  description: |
    SIRIUS is a domain specific library for electronic structure calculations. It implements pseudopotential plane wave (PP-PW) and full potential linearized augmented plane wave (FP-LAPW) methods and is designed for GPU acceleration of popular community codes such as Exciting, Elk and Quantum ESPRESSO.
  doc_url: https://electronic-structure.github.io/SIRIUS-doc/
  dev_url: https://github.com/electronic-structure/SIRIUS

extra:
  recipe-maintainers:
    - AdhocMan
    - ltalirz
    - toxa81
    - simonpintarelli
