schema_version: 1

context:
  version: 7.12.0
  mpi_prefix: "mpi_${{ mpi }}"

package:
  name: sirius
  version: ${{ version }}

source:
  - url: https://github.com/electronic-structure/SIRIUS/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 25d14a31faf9cd07b19a327aba5f8f024be63cf6d9d033eada4410727bf95ce9

build:
  number: 0
  string: mpi_${{ mpi }}_h${{ hash }}_${{ build_number }}
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ compiler("fortran") }}
    - ${{ mpi }}
    - cmake >=3.25
    - doxygen
    - ninja >=1.13
    - pkg-config
  host:
    - ${{ mpi }}
    - _openmp_mutex
    - "costa * ${{ mpi_prefix }}_*"
    - fmt
    - gsl >=2.8
    - hdf5
    #  - "libvdwxc * ${{ mpi_prefix }}_*"
    - libxc-c
    - "openblas * *openmp_*"
    - pugixml
    - scalapack
    - "spfft * ${{ mpi_prefix }}_*"
    - "spla * ${{ mpi_prefix }}_*"
    - spglib
    - zlib
  run:
    - ${{ mpi }}
    - _openmp_mutex
    - "costa * ${{ mpi_prefix }}_*"
    - fmt
    - gsl >=2.8
    - libxc-c
    - "openblas * *openmp_*"
    - scalapack
    - "spfft * ${{ mpi_prefix }}_*"
    - "spla * ${{ mpi_prefix }}_*"

tests:
  - package_contents:
      lib:
        - libsirius
        - libsirius_cxx
  - script:
      - if: target_platform == build_platform
        then:
          - atom --help
          - hydrogen --help

about:
  homepage: https://github.com/electronic-structure/SIRIUS
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Domain specific library for electronic structure calculations
  description: |
    SIRIUS is a domain specific library for electronic structure calculations.
    It implements pseudopotential plane wave (PP-PW) and full potential
    linearized augmented plane wave (FP-LAPW) methods and is designed for GPU
    acceleration of popular community codes such as Exciting, Elk and Quantum
    ESPRESSO.
  repository: https://github.com/electronic-structure/SIRIUS
  documentation: https://electronic-structure.github.io/SIRIUS-doc/

extra:
  recipe-maintainers:
    - toxa81
    - simonpintarelli
    - AdhocMan
    - mkrack
